spring.application.name=marketManagement

#1
spring.datasource.url=jdbc:sqlite:db/orders.db
#2
spring.datasource.driver-class-name=org.sqlite.JDBC
#3
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
#4
spring.jpa.hibernate.ddl-auto=none
#5
spring.sql.init.mode=never
#6
spring.jpa.show-sql=true
#7
server.error.include-stacktrace=never
#8
server.error.include-message=always


#1 - Especificando a URL de conexão com o banco de dados.
#2 - Nome do driver JDBC utilizado
#3 - O Hibernate não suporta SQLite oficialmente. É gerado um SQL compatível com SQLite
#4 - Nega a produção automatica de tabelas do hibernate.
#5 - Controla a execução do schemaSQL
#6 - Mostra SQL no console/log.
#7 - Controla se erros exibem stacktrace.
#8 - Controla se resposta de erro inclui a mensagem.